### PR TITLE
Add missing Service Group for integration tests

### PR DESCRIPTION
**Pull request by Woellchen**

### CODE REVIEW

**Review by TuxPowered42 — APPROVED** [review]

**Comment by Woellchen** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Comment by kofrezo** [comment]
test this please

**Comment by kofrezo** [comment]
test this please

**Comment by kofrezo** [comment]
test this please

**Comment by kofrezo** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Comment by kofrezo** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Comment by Woellchen** [comment]
test this please

**Pull request closed without merging**
