### PR TITLE
Remove unused __repr__()s from hypervisor_preferences.py

### PR DESCRIPTION
**Pull request by hasegeli**

### CODE REVIEW

**Comment by hasegeli** [comment]
I was reading this again and noticed those now being unneeded.  It is not tested but unlikely to fail.

**Comment by HerrSpace** [comment]
Why remove the hash difference? It seems like a sane idea.

**Comment by HerrSpace** [comment]
retest this please

**Comment by hasegeli** [comment]
`sorted_hypervisors()` sorts `([preference, ...], hypervisor)`s tuples.  I think the hypervisors would be sorted stably if all preferences happen to return the same value.

**Comment by HerrSpace** [comment]
The tests fail by raising a bunch of these:
```
        # Use decorate-sort-undecorate pattern to log details about sorting
        for comparables, hypervisor in sorted(
            ([LazyCompare(p, vm, h) for p in preferences], h)
>           for h in hypervisors
        ):
E       TypeError: unorderable types: Hypervisor() < Hypervisor()

igvm/hypervisor_preferences.py:151: TypeError
```

**Comment by hasegeli** [comment]
Oh, I missed that the objects don't compare by default on Python 3.  I removed that commit from the request.

**Comment by HerrSpace** [comment]
This seems somewhat pointless to me now. Having the __repr__s is kinda usefull for printf debugging during development.

**Pull request closed without merging**
