### PR TITLE
Use single AWS SG per VM but don't create it

### PR DESCRIPTION
**Pull request by TuxPowered42**

### CODE REVIEW

**Review by lacunoc — APPROVED** [review]
lgtm

**Comment by TuxPowered42** [comment]
retest this please

**Comment by TuxPowered42** [comment]
retest this please

**Comment by TuxPowered42** [comment]
retest this please

**Comment by TuxPowered42** [comment]
retest this please

**Comment by TuxPowered42** [comment]
retest this please

**Comment by TuxPowered42** [comment]
retest this please

**Comment by TuxPowered42** [comment]
retest this please

**Pull request merged**
