### PR TITLE
Mitigate network and puppetrun issues

### PR DESCRIPTION
**Pull request by kofrezo**
Tests seem to randomly fail because of time outs. I am unsure if this is
due to network interruptions or timing issues in the order of executing
commands.

Maybe this helps.

### CODE REVIEW

**Comment by kofrezo** [comment]
test this please.

**Comment by kofrezo** [comment]
test this please.

**Comment by kofrezo** [comment]
test this please.

**Comment by kofrezo** [comment]
test this please.

**Comment by kofrezo** [comment]
test this please.

**Comment by kofrezo** [comment]
There seem to be 2 main reasons why many igvm operations fail in the test environment (pipeline) and real world:

1. fabric.exceptions.NetworkError: Timed out trying to connect to [...]
2. igvm.exceptions.VMError: Initial puppetrun failed

Both are mitigated in this PR by adding retries for the operations failing. 

First one seems happen because of network interruptions (expected and unexpected). Second one seems to happen because of problems connecting to the Puppetserver or the Puppetserver being unavailable due to restarts, bugs etc. 

Since we can't fix all of the root causes and some of them are "normal" to happen it seems to me like a good idea to make the operations more robust by doing a retry.

**Comment by kofrezo** [comment]
test this please.

**Comment by kofrezo** [comment]
test this please.

**Comment by kofrezo** [comment]
test this please.

**Review by TuxPowered42 — APPROVED** [review]

**Review by lamaral — APPROVED** [review]

**Pull request merged**
